version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    networks:
      - app-network
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=password

  app:
    build: app
    restart: always
    networks:
      - app-network
      - web-network

  web:
    build: web
    restart: always
    ports:
      - 80:80
    networks:
      - web-network
  
  networks:
    app-networks:
    web-networks: